project:
  type: default
  output-dir: ../release/manuscript
  render:
    - methods/index.qmd
    - nzmj/index.qmd
execute:
  freeze: auto
  echo: false
  warning: false
bibliography: references.bib
format:
  html:
    toc: true
  docx: default
  pdf:
    documentclass: article
